name: TruffleHog Secret Scan on PR

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  pull-requests: write  
  contents: read

jobs:
  trufflehog_scan:
    name: TruffleHog Secret Scan 🔎 🔒
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TruffleHog Binary
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          trufflehog --version

      - name: Get Changed Files in PR
        id: changed-files
        run: |
          BASE_SHA=$(git merge-base origin/${{ github.base_ref }} HEAD)
          HEAD_SHA="${{ github.sha }}"
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" | tr '\n' ' ')
          if [ -z "$CHANGED_FILES" ]; then
            echo "CHANGED_FILES=none" >> $GITHUB_ENV
          else
            echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          fi

      - name: Run TruffleHog on PR Changed Files
        id: trufflehog_scan
        run: |
          SCAN_RESULTS=""
          SECRET_FOUND=false
          
          if [ "${{ env.CHANGED_FILES }}" = "none" ]; then
            echo "No files to scan."
            SCAN_RESULTS="No files changed in this PR."
          else
            for file in ${{ env.CHANGED_FILES }}; do
              if [[ -f "$file" ]]; then
                echo "Scanning $file..."
                RESULT=$(trufflehog filesystem --no-verification "$file" 2>&1 || true)
                echo "$RESULT"
                SCAN_RESULTS+="$RESULT"$'\n\n'
                
                if echo "$RESULT" | grep -q 'Detector Type:'; then
                  SECRET_FOUND=true
                fi
              else
                echo "Skipping $file - not found."
                SCAN_RESULTS+="File $file not found in checkout"$'\n\n'
              fi
            done
          fi

          echo "$SCAN_RESULTS" > scan_results.txt
          echo "SECRET_FOUND=$SECRET_FOUND" >> $GITHUB_ENV
          echo "Scan completed."

      - name: Upload Scan Results as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TruffleHog-Scan-Results
          path: scan_results.txt
          retention-days: 5

      - name: Comment on PR with Scan Results
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🔍 **TruffleHog Scan Results** 🔍
            - ✅ Scan **Completed**
            - 🚀 Repository: ${{ github.repository }}
            - 📄 Files Scanned: ${{ env.CHANGED_FILES == 'none' && 'None' || env.CHANGED_FILES }}
            **Results:**
            ${{ env.SECRET_FOUND == 'true' && '- ❌ Secrets detected! Please rotate secrets before merging.' || '- ✅ No secrets found!' }}
            **Scan Details:** [View Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ${{ env.SECRET_FOUND == 'true' && '**Note:** This PR can still be merged, but secret rotation is recommended.' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set Workflow Status
        if: always()
        run: |
          if [ "${{ env.SECRET_FOUND }}" = "true" ]; then
            echo "Secrets found, but allowing merge with warning"
            exit 0
          else
            echo "No secrets found"
            exit 0
          fi
